version: '3.7'

services:

  # db:
  #   ports: ["127.0.0.1:5432:5432"]

  front:
    ports: ["127.0.0.1:3000:3000"]

  back:
    ports: ["127.0.0.1:5000:5000"]
    command: uvicorn main:app --reload --host 0.0.0.0 --port 5000 --root-path /api/v1
